// 
// Env is generated by `wrangler types` — run it whenever you change your config.
// Do not manually define Env — it drifts from your actual bindings.

/**
 * CRITICAL: Using Portuguese route names to match Angular app!
 * These must align with app-routing.module.ts routes
 */

/**
 * PUBLIC ROUTES - No authentication required, can be accessed by anyone
 * These include: login, registration, password recovery, and error pages
 */
const PUBLIC_ROUTES = [
  "/login",           // Login page
  "/cadastro",        // Registration page
  "/recuperar-senha", // Request password reset
  "/reset-senha",     // Password reset form (accessed via email link with recovery token)
  "/link-invalido",   // Invalid/expired recovery link page
];

/**
 * PROTECTED ROUTES - Require authentication
 * User will be redirected to login if not authenticated.
 * After login, access is controlled by roles in router guards.
 */
const PROTECTED_ROUTES = [
  "/home",           // Home dashboard
  "/professor",      // Teacher dashboard (Portuguese)
  "/aluno",          // Student dashboard (Portuguese)
  "/administrador",  // Admin dashboard (Portuguese)
  "/videos",         // Video gallery/streaming
];

/**
 * Helper to check if route is public
 */
function isPublicRoute(pathname: string): boolean {
  return PUBLIC_ROUTES.some(route => pathname === route || pathname.startsWith(route + '/'));
}

/**
 * Check if the request has valid authentication
 */
function isAuthenticated(request: Request): boolean {
  const authHeader = request.headers.get("Authorization");
  const cookieHeader = request.headers.get("Cookie");
  
  // Check for JWT token in Authorization header (from Supabase)
  if (authHeader?.startsWith("Bearer ")) {
    return true;
  }
  
  // Check for auth cookies from Supabase
  if (cookieHeader?.includes("sb-")) {
    return true;
  }
  
  return false;
}

/**
 * Determine if a route is protected (requires authentication)
 */
function isProtectedRoute(pathname: string): boolean {
  return PROTECTED_ROUTES.some(route => pathname === route || pathname.startsWith(route + '/'));
}

/**
 * Set security headers on responses
 */
function setSecurityHeaders(response: Response): Response {
  const headers = new Headers(response.headers);
  
  // Prevent caching of sensitive content
  headers.set("Cache-Control", "private, no-cache, no-store, must-revalidate");
  headers.set("Pragma", "no-cache");
  headers.set("Expires", "0");
  
  // Security headers
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("X-Frame-Options", "SAMEORIGIN");
  headers.set("X-XSS-Protection", "1; mode=block");
  
  return new Response(response.body, { 
    status: response.status,
    statusText: response.statusText,
    headers 
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const pathname = url.pathname;

    console.info("→ [Route-Manager] Incoming request", {
      method: request.method,
      pathname,
      isPublic: isPublicRoute(pathname),
      isProtected: isProtectedRoute(pathname),
    });

    /**
     * AUTH CHECK: Block unauthorized access to protected routes
     * 
     * IMPORTANT: Public recovery routes like /reset-senha should be accessible
     * even without authentication because they only need the hash token from email.
     * The frontend will handle the recovery flow.
     */
    if (isProtectedRoute(pathname) && !isAuthenticated(request)) {
      console.warn(`⛔ [Route-Manager] Unauthorized access attempt to protected route: ${pathname}`);
      
      // Redirect to login with return URL so user goes back after login
      const loginUrl = new URL("/login", url.origin);
      loginUrl.searchParams.set("returnUrl", encodeURIComponent(pathname + url.search + url.hash));
      
      return Response.redirect(loginUrl.toString(), 302);
    }

    // Public routes and authenticated requests proceed to frontend
    if (isPublicRoute(pathname)) {
      console.log(`✓ [Route-Manager] Allowing public route: ${pathname}`);
    } else if (isAuthenticated(request)) {
      console.log(`✓ [Route-Manager] Allowing authenticated request to: ${pathname}`);
    }

    // Route to appropriate worker based on path
    let targetService = null;
    let targetUrl = "";

    // API requests go to API_WORKER
    if (pathname.startsWith("/api/")) {
      targetService = env.API_WORKER;
      targetUrl = `https://api-worker.example.com${pathname}${url.search}`;
    } 
    // Everything else (SPA routes) goes to FRONTEND_WORKER
    else {
      targetService = env.FRONTEND_WORKER;
      // Important: Preserve hash for recovery tokens and auth callbacks
      targetUrl = `https://frontend-worker.example.com${pathname}${url.search}${url.hash}`;
    }

    try {
      // Create new request with proper headers
      const newRequest = new Request(targetUrl, {
        method: request.method,
        headers: request.headers,
        body: request.method !== "GET" && request.method !== "HEAD" 
          ? await request.clone().arrayBuffer() 
          : undefined,
      });

      // Fetch from the target service
      const response = await targetService.fetch(newRequest);

      // Apply security headers to all responses
      const securedResponse = setSecurityHeaders(response);

      console.info("✓ Response sent", {
        status: response.status,
        pathname,
      });

      return securedResponse;
    } catch (error) {
      console.error("✗ Error processing request", {
        pathname,
        error: error instanceof Error ? error.message : String(error),
      });

      // Return 502 Bad Gateway on service binding failure
      return new Response("Service temporarily unavailable", {
        status: 502,
        headers: { "Content-Type": "text/plain" },
      });
    }
  },
} satisfies ExportedHandler<Env>;

