// 
// Env is generated by `wrangler types` — run it whenever you change your config.
// Do not manually define Env — it drifts from your actual bindings.

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
        // Get the path and query string from the original request
    const url = new URL(request.url);
    const pathAndQuery = url.pathname + url.search; // e.g., "/api/users?page=2"

    // Build a new URL for the service binding.
    // You can use any origin – the target Worker will receive this full URL.
    const targetUrl = `http://frontend-worker/${pathAndQuery}`;

    // Create a new request to forward
    const newRequest = new Request(targetUrl, {
      method: request.method,
      headers: request.headers,
      body: request.body,
    });

    // Forward the request via the service binding
    return env.FRONTEND_WORKER.fetch(newRequest);
  },
} satisfies ExportedHandler<Env>;

async function fetchBootstrapData(
  env: Env,
  pathname: string,
  headers: Headers,
): Promise<unknown | null> {
  try {
    const res = await fetch(`${env.API_BASE_URL}/api/bootstrap`, {
      headers: {
        Cookie: headers.get("Cookie") || "",
        "X-Request-Path": pathname,
      },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    // If the API is down, the shell still loads and the SPA
    // falls back to client-side data fetching.
    return null;
  }
}

