// 
// Env is generated by `wrangler types` — run it whenever you change your config.
// Do not manually define Env — it drifts from your actual bindings.

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Create a new request to forward to the FRONTEND_WORKER service binding
    const newRequest = new Request(url.toString(), {
      method: request.method,
      headers: request.headers,
      body: request.body,
    });

    // Use service binding to fetch from FRONTEND_WORKER
    return await env.FRONTEND_WORKER.fetch(newRequest);
  },
} satisfies ExportedHandler<Env>;

async function fetchBootstrapData(
  env: Env,
  pathname: string,
  headers: Headers,
): Promise<unknown | null> {
  try {
    const res = await fetch(`${env.API_BASE_URL}/api/bootstrap`, {
      headers: {
        Cookie: headers.get("Cookie") || "",
        "X-Request-Path": pathname,
      },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    // If the API is down, the shell still loads and the SPA
    // falls back to client-side data fetching.
    return null;
  }
}

