name = "espaco-do-saber-video-processing"
main = "src/worker.py"
compatibility_date = "2026-03-05"

[[r2_buckets]]
binding = "VIDEOS_BUCKET"
bucket_name = "espaco-do-saber-videos"

[vars]
APP_ENV = "production"
